apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: openshiftpulse
  namespace: {{ include "openshiftpulse.namespace" . }}
  labels:
    {{- include "openshiftpulse.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "openshiftpulse.selectorLabels" . | nindent 6 }}
---
{{- if .Values.quota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: openshiftpulse
  namespace: {{ include "openshiftpulse.namespace" . }}
spec:
  hard:
    pods: {{ .Values.quota.pods | quote }}
    requests.cpu: {{ .Values.quota.requestsCpu | quote }}
    requests.memory: {{ .Values.quota.requestsMemory | quote }}
    limits.cpu: {{ .Values.quota.limitsCpu | quote }}
    limits.memory: {{ .Values.quota.limitsMemory | quote }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: openshiftpulse
  namespace: {{ include "openshiftpulse.namespace" . }}
spec:
  limits:
  - type: Container
    default:
      cpu: 200m
      memory: 256Mi
    defaultRequest:
      cpu: 50m
      memory: 64Mi
    max:
      cpu: "1"
      memory: 1Gi
  - type: Pod
    max:
      cpu: "2"
      memory: 2Gi
{{- end }}
